version: '2'

services:
   mailhog:
    image: madebyewave/mailhog
    env_file: ./.env
    container_name: mailer
    restart: always    
    ports:
       - "${MAILHOG_PORT}:8025"
    networks:
       - env_devbox-network

networks:
   env_devbox-network:
     external: true